### ISSUE TITLE
Fetch container logs by a workflow job name

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sqlflow#1367]
Consider the follow Argo workflow description in YAML format. It has three steps. And the execution of the workflow is running each step one-by-one.
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello
  templates:
  - name: hello-hello-hello
    steps:
    - - name: hello1
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2"
    - - name: hello3
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"

  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

We submit the following Argo YAML file via `kubectl create -f workflow.yaml` and receive the workflow job name as `steps-7lxxs`.

The problem is, how can we get the container logs of each step using the job name?
