### ISSUE TITLE
env spec in argo YAML should be quoted

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#1766]
The env spec of Argo YAML which generated by Couler is like:
``` yaml
env:
- name: SQLFLOW_EXIT_ON_SUBMIT
    value: false
``` 

The value should be quota by `""`:

``` yaml
env:
- name: SQLFLOW_EXIT_ON_SUBMIT
    value: "false"
```

otherwise, workflow doesn't work:

``` 
> kubectl describe wf ..
Status:
  Finished At:  2020-01-21T03:11:09Z
  Message:      invalid spec: unrecognized type: string
  Phase:        Failed
  Started At:   2020-01-21T03:11:09Z
Events:         <none>
```
