### ISSUE TITLE
Support TTL for the Argo workflow

### ISSUE THREAD

**Issue by Yancey0623** [sql-machine-learning/sqlflow#1824]
Argo workflow support TTL feature to remove it after several seconds, an example workflow YAML is as the following:

``` yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: gc-ttl-
spec:
  ttlStrategy:
    secondsAfterCompletion: 10 # Time to live after workflow is completed, replaces ttlSecondsAfterFinished
    secondsAfterSuccess: 5     # Time to live after workflow is successful
    secondsAfterFailure: 5     # Time to live after workflow fails
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
     args: ["hello world"]
```
