### ISSUE TITLE
High-level representation for Argo

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sqlflow#959]
This issue serves as the design draft following https://github.com/sql-machine-learning/sqlflow/blob/develop/doc/design/design_workflow.md.

We hope to propose a Python package as a higher-level representation of Argo's YAML specification. Users can write Python programs calling APIs provided by this package. The Python programs can run and implement a workflow.  

We hope we can also write a compiler/transpiler `pyargo` to convert the Python program into an Argo YAML specification.

To realize this design, let us go over the examples in https://github.com/argoproj/argo/blob/master/examples/README.md one-by-one and rewrite each using this imaginary API.

**Comment by wangkuiyi** [comment]
## Hello World!

`pyargo` generates the following YAML spec

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow                  # new type of k8s spec
metadata:
  generateName: hello-world-    # name of the workflow spec
spec:
  entrypoint: whalesay          # invoke the whalesay template
  templates:
  - name: whalesay              # name of the template
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]
      resources:                # limit the resources
        limits:
          memory: 32Mi
          cpu: 100m
```

from this Python program

```python
# In Python module hello-world.py:
def whalesay():
    pyargo.run_docker(image="docker/whalesay", command=["cowsay"], args=["hello world"],
                      memory="32Mi", cpu="100m")
whalesay()
```

The information mapping from the Python program into the YAML spec:

- `metadata.generateName`: the Python source filename plus `-`.
-  `spec.entrypoint`: the only one function call in the global scope.
- `spec.templates[0].name`: the name of the first function defined in the global scope.
- `spec.templates[0].container`: the call to `pyargo.run_docker`.

**Comment by wangkuiyi** [comment]
## Parameters

Let's look at a slightly more complex workflow spec with parameters.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-parameters-
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: hello world

  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message       # parameter declaration
    container:
      # run cowsay with that message input parameter as args
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

```go
# In Python module hello-world-parameters.py:
def whalesay(message):
    pyargo.run_docker(image="docker/whalesay", command=["cowsay"], args=[message],
                      memory="32Mi", cpu="100m")

message = pyargo.Option(default_value="hello_world")
whalesay(message)
```

We need `pyargo.Option` to create and parse a command-line option because Argo allows arguments of the entrypoint to be customizable from the command line.

**Comment by wangkuiyi** [comment]
## Command-line Options


```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: global-parameters-
spec:
  entrypoint: A
  arguments:
    parameters:
    - name: log-level
      value: INFO

  templates:
  - name: A
    container:
      image: containerA
      env:
      - name: LOG_LEVEL
        value: "{{workflow.parameters.log-level}}"
      command: [runA]
  - name: B
    container:
      image: containerB
      env:
      - name: LOG_LEVEL
        value: "{{workflow.parameters.log-level}}"
      command: [runB]
```

```python
log_level = pyargo.Option(default_value="INFO")

def A():
    pyargo.run_docker(image="containerA", env={"LOG_LEVEL": log_level}, command=["runA"])

def B():
    pyargo.run_docker(image="containerB", env={"LOG_LEVEL": log_level}, command=["runB"])

A(log_level)
```

**Comment by wangkuiyi** [comment]
## Steps

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello

  # This spec contains two templates: hello-hello-hello and whalesay
  templates:
  - name: hello-hello-hello
    # Instead of just running a container
    # This template has a sequence of steps
    steps:
    - - name: hello1            # hello1 is run before the following steps
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2a           # double dash => run after previous step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2a"
      - name: hello2b           # single dash => run in parallel with previous step
        template: whalesay
        arguments:
          parameters:
          - name: message
            value: "hello2b"

  # This is the same template as from the previous example
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

```python
def hello_hello_hello():
    whalesay(message="hello1")
    pyargo.concurrent(
        lambda: whalesay(message="hello2a"),
        lambda: whalesay(message="hello2b"))

def whalesay(message):
    pyargo.run_docker(image="docker/whalesay", command=["cowsay"], args=[message])
```

**Comment by wangkuiyi** [comment]
## DAG

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]
```

```python
def echo(message):
    pyargo.run_docker(image="alpine:3.7", command=["echo", message])

def diamond():
    pyargo.dag([
        {name: "A", lambda: echo(message="A")},
        {name: "B", lambda: echo(message="B"), dependencies=["A"]},
        {name: "C", lambda: echo(message="C"), dependencies=["A"]},
        {name: "D", lambda: echo(message="D"), dependencies=["B", "C"]}])
```

**Comment by merlintang** [comment]
I suggest we choose to define the DAG or pipeline at first, then call each function from one node of DAG.  Below is the option one: 

```python

# generics
T = TypeVar('T')
# type alias: either a string or a list of string
StringOrStringList = Union[str, List[str]]

# define a job 
def whalesay(args: StringOrStringList, dag:DAG):
    return BashJob(
    task_id='whalesay',
    docker_image= 'docker/whalesay'
    bash_command='cowsay',
    args = args,
    dag=dag)

# define a pipeline 
@pyargo.pipeline(
  name='hello world example',
  description='run a bash job from a container'
)
def hello_world_example(message: str):
    default_args = {
    'owner': 'test',
    'start_date': datetime(2019, 10, 08),
    'email': [xxx@example.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
    }

    pipeline = DAG('tutorial', default_args=default_args, schedule_interval=timedelta(days=1))
    whalesay(message,  pipeline)
```
then we can run this pipeline via compile function 
```python
# compile to local file for verify
pyargo.compiler.compile(hello_world_example()).tolocal("hello_world.yaml")

# compile the file and send it to k8s cluster 
cluster_config = {
   "namespace": "test",
   "owner": "test",
}
paras = []
message = PipelineParam(name="message", value="hello world")
paras.append(message)
pyargo.compiler.compile(hello_world_example()).tocluster(config=cluster_config, paras = pars)

```

**Comment by merlintang** [comment]
Or the option 2: 
```python
# generics
T = TypeVar('T')
# type alias: either a string or a list of string
StringOrStringList = Union[str, List[str]]

# define a job 
def whalesay(args: StringOrStringList):
    return BashJob(
    task_id='whalesay',
    docker_image= 'docker/whalesay'
    bash_command='cowsay',
    args = args,
    )

def hello_world_example(message: str):
    default_args = {
    'owner': 'test',
    'start_date': datetime(2019, 10, 08),
    'email': [xxx@example.com'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
    }

   with DAG('tutorial', default_args=default_args, schedule_interval=timedelta(days=1)):
         whalesay(message)
```

**Comment by tonyyang-svail** [comment]
Hi @wangkuiyi @merlintang, @typhoonzero mentioned the following in our daily meeting:

"Looks like this library will be written in Python, is it possible to use Go? Because the SQLFlow core (server, parser etc.) is written in Go, converting from Go struct to YAML is more straightforward."

**Comment by wangkuiyi** [comment]
@tonyyang-svail Yes, I remember @typhoonzero 's comment. I think we can do a Go version and a Python one.

**Comment by wangkuiyi** [comment]
@merlintang Let us go for a design that (1) requires less coding work from the users and (2) makes the code comprehensive.

**Comment by wangkuiyi** [comment]
## Artifacts

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: generate-artifact
        template: whalesay
    - - name: consume-artifact
        template: print-message
        arguments:
          artifacts:
          # bind message to the hello-art artifact
          # generated by the generate-artifact step
          - name: message
            from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      # generate hello-art artifact from /tmp/hello_world.txt
      # artifacts can be directories as well as files
      - name: hello-art
        path: /tmp/hello_world.txt

  - name: print-message
    inputs:
      artifacts:
      # unpack the message input artifact
      # and put it at /tmp/message
      - name: message
        path: /tmp/message
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["cat /tmp/message"]
```

```python
def artifact_example():
    artifact_hello_art = whalesay()
    print_message(artifact_hello_art)

def whalesay():
    pyargo.run_docker(image="docker/whalesay", command=["ls", "-c"], args=["sawsay hello world | tee /tmp/hello_world.txt"])
    return pyargo.artifact("/tmp/hello_world.txt")

def print_message(artifact_message):
    pyargo.unpack_artifact(message, "/tmp/message")
    pyargo.run_docker(image="alpine", command=["sh", "-c"], args=["cat /tmp/message"]) 
```
